# pyright: reportArgumentType=false, reportUntypedFunctionDecorator=false
"""
FastHTML Welcome App (idiomatic FastHTML, see copilot-instructions.md and fasthtml-llms-ctx.txt)

NOTE: FastTags (Div, H1, P, A, Titled, etc.) are dynamically generated by FastHTML and not visible to static analysis.
Suppression of static analysis errors is handled via settings.json, as required and documented for this framework.
"""

from fasthtml.common import *


app, rt = fast_app()


@rt
def index():
    """Welcome page with link to ToDo app."""
    return Titled(
        "Welcome to FastHTML!",
        Div(
            H1("Welcome to FastHTML!"),
            P("This is your starter project for building HTML-first Python web apps."),
            P(A("Go to ToDo App", href="/todo")),
        ),
    )


@rt("/todo")
def todo():
    """Simple ToDo app placeholder."""
    return Titled(
        "ToDo App",
        Div(
            H1("ToDo App"),
            P("This is where your ToDo app will go!"),
            P(A("Back to Home", href="/")),
        ),
    )


def main() -> None:
    serve()
