# pyright: reportArgumentType=false, reportUntypedFunctionDecorator=false
"""
FastHTML Welcome App (idiomatic FastHTML, see copilot-instructions.md and fasthtml-llms-ctx.txt)

NOTE: FastTags (Div, H1, P, A, Titled, etc.) are dynamically generated by FastHTML and not visible to static analysis.
Suppression of static analysis errors is handled via settings.json, as required and documented for this framework.
"""

import logging
from fasthtml.common import *
from fasthtml.common import Mount


from app.views.weekly_overview import weekly_overview_app
from app.views.add_gratitude import add_gratitude_app
from app.views.add_good_thing import good_thing_app
from app.views.add_affirmation import affirmation_app
from app.views.add_quote import quote_app


app, rt = fast_app(
    routes=[
        Mount("/weekly-overview", weekly_overview_app, name="weekly_overview"),
        Mount("/add-gratitude", add_gratitude_app, name="add_gratitude"),
        Mount("/add-good-thing", good_thing_app, name="add_good_thing"),
        Mount("/add-affirmation", affirmation_app, name="add_affirmation"),
        Mount("/add-quote", quote_app, name="add_quote"),
    ]
)


@rt("/")
def index():
    return Titled(
        "Gratitude and Positivity Journal",
        Div(
            P("This is your gratitude and positivity journal app."),
            Ul(
                Li(A("Add Gratitude Item", href="/add-gratitude")),
                Li(A("Add Good Thing That Happened", href="/add-good-thing")),
                Li(A("Add Affirmation", href="/add-affirmation")),
                Li(A("Add Positive Quote", href="/add-quote")),
                Li(A("Weekly Overview", href="/weekly-overview")),
            ),
        ),
    )


def main() -> None:

    our_logger = logging.getLogger("uvicorn")
    our_logger.info("Uvicorn running on http://localhost:5001 (Press CTRL+C to quit)")
    serve()
